apiVersion: v1
data:
  application.yaml: |
    quarkus:
      kubernetes-client:
        trust-certs: true
      kubernetes-config:
        enabled: true
        config-maps:
          - inventory-config
      hibernate-orm:
        database:
          generation: drop-and-create
        sql-load-script: load.sql
      datasource:
        # db-kind: h2
        # jdbc:
        #   url: jdbc:h2:mem:customers;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        db-kind: postgresql
        jdbc:
          url: jdbc:postgresql://inventory-postgresql:5432/inventory
      log:
        level: INFO
      jaeger:
        endpoint: http://jaeger-all-in-one-inmemory-collector:14268/api/traces
        sampler-type: const
        sampler-param: 1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: inventory
    meta.helm.sh/release-namespace: inventory-erik
  creationTimestamp: "2021-08-31T16:59:37Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:application.yaml: {}
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/managed-by: {}
    manager: helm
    operation: Update
    time: "2021-08-31T16:59:37Z"
  name: inventory-config
  namespace: inventory-erik-tgt
  resourceVersion: "50016329"
  selfLink: /api/v1/namespaces/inventory-erik/configmaps/inventory-config
  uid: 84976879-ceab-46d2-90f4-ed0f6723bfee
