apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: inventory
    meta.helm.sh/release-namespace: inventory-erik
  labels: {}
  name: default-view
  namespace: inventory-erik-tgt
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/inventory-erik/rolebindings/default-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: default
