apiVersion: v1
data:
  postgresql-password: aW52ZW50b3J5
  postgresql-postgres-password: a3Q0YTZDVEw1eA==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: inventory
    meta.helm.sh/release-namespace: inventory-erik
  creationTimestamp: "2021-08-31T16:59:37Z"
  labels:
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.9.2
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:postgresql-password: {}
        f:postgresql-postgres-password: {}
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:helm.sh/chart: {}
      f:type: {}
    manager: helm
    operation: Update
    time: "2021-08-31T16:59:37Z"
  name: inventory-postgresql
  namespace: inventory-erik-tgt
  resourceVersion: "50016327"
  selfLink: /api/v1/namespaces/inventory-erik/secrets/inventory-postgresql
  uid: d9d893cd-f7cf-4626-9901-3e21f3a74d74
type: Opaque
