apiVersion: v1
data:
  application.yaml: cXVhcmt1czoKICBkYXRhc291cmNlOgogICAgdXNlcm5hbWU6IGludmVudG9yeQogICAgcGFzc3dvcmQ6IGludmVudG9yeQo=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: inventory
    meta.helm.sh/release-namespace: inventory-erik
  creationTimestamp: "2021-08-31T16:59:37Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:application.yaml: {}
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/managed-by: {}
      f:type: {}
    manager: helm
    operation: Update
    time: "2021-08-31T16:59:37Z"
  name: inventory-secret
  namespace: inventory-erik-tgt
  resourceVersion: "50016328"
  selfLink: /api/v1/namespaces/inventory-erik/secrets/inventory-secret
  uid: db5a20f8-ecc9-44b2-b222-064a16f773ea
type: Opaque
