apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: inventory
    meta.helm.sh/release-namespace: inventory-erik
  labels:
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.9.2
  name: inventory-postgresql
  namespace: inventory-erik-tgt
  selfLink: /api/v1/namespaces/inventory-erik/services/inventory-postgresql
spec:
  ports:
  - name: tcp-postgresql
    port: 5432
    protocol: TCP
    targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/name: postgresql
    role: primary
  sessionAffinity: None
  type: ClusterIP
