apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's http port
    meta.helm.sh/release-name: inventory
    meta.helm.sh/release-namespace: inventory-erik
  labels:
    app: inventory
  name: inventory
  namespace: inventory-erik-tgt
  selfLink: /api/v1/namespaces/inventory-erik/services/inventory
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: inventory
  sessionAffinity: None
  type: ClusterIP
