apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: inventory
    meta.helm.sh/release-namespace: inventory-erik
  creationTimestamp: "2021-08-31T16:59:37Z"
  labels:
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.9.2
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:helm.sh/chart: {}
          f:service.alpha.kubernetes.io/tolerate-unready-endpoints: {}
      f:spec:
        f:clusterIP: {}
        f:ports:
          .: {}
          k:{"port":5432,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:publishNotReadyAddresses: {}
        f:selector:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: helm
    operation: Update
    time: "2021-08-31T16:59:37Z"
  name: inventory-postgresql-headless
  namespace: inventory-erik-tgt
  resourceVersion: "50016331"
  selfLink: /api/v1/namespaces/inventory-erik/services/inventory-postgresql-headless
  uid: 047ab29b-fd1f-493f-a159-9c4ef3cf2143
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - name: tcp-postgresql
    port: 5432
    protocol: TCP
    targetPort: tcp-postgresql
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/name: postgresql
  sessionAffinity: None
  type: ClusterIP
